<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-0HRE68P" failures="1" tests="1" name="Test(failed)(failed)(failed)" time="38.236" errors="0" timestamp="2024-05-09T08:13:38 IST">
  <testcase classname="Facebook.Testcase1" name="tc1" time="31.134">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNzE1MjE0NDM3LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D] but found [Error]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://www.facebook.com/login/?privacy_mutation_token=eyJ0eXBlIjowLCJjcmVhdGlvbl90aW1lIjoxNzE1MjE0NDM3LCJjYWxsc2l0ZV9pZCI6MzgxMjI5MDc5NTc1OTQ2fQ%3D%3D] but found [Error]
at Facebook.Testcase1.tc1(Testcase1.java:40)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- tc1 -->
</testsuite> <!-- Test(failed)(failed)(failed) -->
